controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# config/routes.yaml
first_page:
    path: /e00/firstpage
    controller: App\Controller\FirstPageController::index
