<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXZN7TMM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXZN7TMM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXZN7TMM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXZN7TMM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXZN7TMM\App_KernelDevDebugContainer([
    'container.build_hash' => 'XZN7TMM',
    'container.build_id' => '621b2a3b',
    'container.build_time' => 1738071111,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXZN7TMM');
