<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'main_page' => [[], ['_controller' => 'App\\Controller\\MainController::mainPage'], [], [['text', '/e01']], [], [], []],
    'article_page' => [['article'], ['_controller' => 'App\\Controller\\MainController::articlePage'], [], [['variable', '/', '[^/]++', 'article', true], ['text', '/e01']], [], [], []],
];
